[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
ffi = true

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# Allow reading files for cross-platform testing
fs_permissions = [
    { access = "read", path = "." }
]